version: '3.8'

services:
  api:
    container_name: revisa-tu-piel-contenedor-backend
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"  # Cambiado para usar el puerto 81
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    networks:
      local-network:
        aliases:
          - revisa-tu-piel-backend

networks:
  local-network:
    driver: bridge
